### ISSUE TITLE
Put pandoc on the path during a check

### ISSUE THREAD

**Issue by jimhester** [r-lib/rcmdcheck#109]
At least on windows pandoc (as installed by RStudio) is unlikely to be on the system PATH, so R CMD check can't find it, and generates a note.

> N  checking top-level files
   Files 'README.md' or 'NEWS.md' cannot be checked without 'pandoc' being installed.

However `rmarkdown::pandoc_available()` is `TRUE`, so we could probably put that the pandoc on the PATH, e.g. using `withr::with_path(dirname(rmarkdown::pandoc_exec()))` before running `R CMD check`.

**Comment by maheshKulkarniX** [comment]
> **Simple way to resolve this issue Just Add**
`README.md` in **.Rbuildignore File**

**Comment by gaborcsardi** [comment]
Closed by #132
