### ISSUE TITLE
Format check messages so they can be easily ingested by github actions

### ISSUE THREAD

**Issue by jimhester** [r-lib/rcmdcheck#113]
The marker format only allows matching line-by-line, so multi-line errors are challenging to capture, particularly the free form messages output by `R CMD check`.

It would be useful if `rcmdcheck()` had a custom print method to reformat these messages in a way that could be captured more easily by the markers in GitHub actions.

**Comment by gaborcsardi** [comment]
Do you still want this? 

I think if we go this way, then maybe rcmdcheck could just return or save an object that you can process in GHA. Otherwise if we encode every check "record" into a single line, then output will look weird.

**Comment by jimhester** [comment]
We can close it.
