### ISSUE TITLE
Provide helper for checking CRAN package

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#115]
i.e. download package, install devel dependencies, and run R CMD check on `.tar.gz`

I can't quite tell if this would be in scope for rcmdcheck, or would be better off in another package. My motivation is (e.g.) checking ggplot2 as part of the scales github actions.

**Comment by gaborcsardi** [comment]
This could fit here, yeah, or maybe revdepcheck.

**Comment by hadley** [comment]
I haven't felt the need for this again, so feel free to close.
