### ISSUE TITLE
File not found with github actions and renv

### ISSUE THREAD

**Issue by nteetor** [r-lib/rcmdcheck#116]
I have been working on moving a project from travis to github actions. The project uses {renv} and when trying to run `rcmdcheck::rcmdcheck(. . .)` I see the following error `cannot open file 'renv/activate.R': No such file or directory`. The github action workflow can be found [here](https://github.com/nteetor/yonder/commit/df8e108bb08a2366e035fa952a3caa092eb25d4c/checks?check_suite_id=367897040). 

I have only guesses about the source of the error,

1. The folder and script aren't copied to a new directory setup by rcmdcheck
1. The `renv/` folder is listed in my `.Rbuildignore` file, so the folder is dropped during the rcmdcheck process

I'm a little baffled because I would expect renv to be setup before rcmdcheck is run. I believe rcmdcheck launches new R processes, so perhaps in the launched builds the folder no longer exists. Locally, I do not get the same issue. 

I tried finding another project using github actions + rcmdcheck + renv and could not. I hope the error in this case is not solely my own.

**Comment by gaborcsardi** [comment]
I think this is https://github.com/r-lib/callr/issues/139

**Comment by nteetor** [comment]
I had reviewed 139. I'll jump over there to ask about a PR.

**Comment by gaborcsardi** [comment]
Seems like this works fine now, so it was either indeed https://github.com/r-lib/callr/issues/139 or something else has fixed it.
