### ISSUE TITLE
Spell check 

### ISSUE THREAD

**Issue by stevecondylios** [r-lib/rcmdcheck#117]
CRAN submissions appear to be spell checked during auto processing. 

I don’t believe a spell check is performed during `R CMD check --as-cran`

Would it make sense to include it, perhaps with any discoveries returned as `NOTE`s?

**Comment by gaborcsardi** [comment]
You need to set an env var for spell checks: 
```
_R_CHECK_CRAN_INCOMING_USE_ASPELL_=true
```

**Comment by stevecondylios** [comment]
Awesome, I was not aware of this.

**Comment by gaborcsardi** [comment]
It is a CRAN / base R thing, AFAIR not even documented.

**Comment by stevecondylios** [comment]
FWIW I vouch for its usefulness. Has saved me some silly typos a few times

**Comment by jennybc** [comment]
An alternative is to rig up a regular test using the spelling package (<https://docs.ropensci.org/spelling/>). `usethis::use_spell_check()` helps set this up. An advantage to using the spelling package is that it also helps you curate your own whitelist.

**Comment by stevecondylios** [comment]
Very handy. I just found typos that CRAN's checks didn't with `spelling::spell_check_package()` and several more (including one in a variable name) with `spelling::spell_check_files(paste0("R/", dir("R")))`. Thanks so much!

**Comment by gaborcsardi** [comment]
This is a check configuration option, so I would not hardcode it into rcmdcheck.
