### ISSUE TITLE
Check for namespace in examples of unexported functions?

### ISSUE THREAD

**Issue by stevecondylios** [r-lib/rcmdcheck#118]
Could it be useful to check for namespaces e.g. `dplyr:::` prepended to examples for unexported functions? 

E.g. Where `myfunct()` is not exported

```R
#' @examples
#'  myfunct()
```
would not pass, but 

```R
#' @examples
#'  my_package:::myfunct()
```
would pass.

Currently, I don't think checks do this (`--as-cran` or otherwise)

I'm not exactly sure if documentation for unexported functions even matters, since, it may not get used anywhere (other than github or whereever the source is stored)

**Comment by jennybc** [comment]
In these cases, you probably also want `@noRd`. Ask me how I know.

**Comment by stevecondylios** [comment]
Really appreciate the `@noRd` tip, which covers the majority of cases. 

To summarise, if we want to export the function, simply `@export`, and if we don't, use `@noRd` to omit docs for those function. 

There still remains the scenario where the author wishes to include docs for an unexported function. But perhaps this isn't not worth worrying about on account of it being 

1. Rare
2. Solved via compromising on either `@export`ing the function or foregoing docs

But if an author _really_ wanted to document an unexported function, it seems checks pass `--as-cran` when `@usage` is of the form 
```
#' @usage funct()
``` 

but fail when of the form
```
#' @usage package:::funct()
```  
(which should be reversed). But I have no idea if this could break things downstream.

**Comment by gaborcsardi** [comment]
If you want to document an internal function, and include its manual page in the package, use `@keywords internal` without `@noRd`. See e.g. https://blog.r-hub.io/2019/12/12/internal-functions/#how-to-document-internal-functions

**Comment by gaborcsardi** [comment]
I don't there is anything to do in rcmdcheck for this. Please reopen if you think otherwise.
