### ISSUE TITLE
Add option to enable colored output

### ISSUE THREAD

**Issue by jimhester** [r-lib/rcmdcheck#119]
Right now if the autodetection fails you can set crayon options to turn on color for the rcmdcheck output, e.g. `options(crayon.enabled = TRUE)`.

For the GitHub Actions use case it would be useful to have a rcmdcheck specific option or environment variable to control this, then the [setup-r](https://github.com/r-lib/actions/tree/master/setup-r) action can enable this without affecting color elsewhere in the workflow, e.g. https://github.com/hadley/mastering-shiny/issues/132

**Comment by jimhester** [comment]
This would still be somewhat useful to have a rcmdcheck specific option to control the color, but for now we are setting the crayon option before running `rcmdcheck()`, which works ok.

**Comment by gaborcsardi** [comment]
Closed by #126, right @jimhester?

**Comment by jimhester** [comment]
yeah
