### ISSUE TITLE
Print test(that) result summary in the summary

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rcmdcheck#121]

**Comment by hadley** [comment]
Could print from the last line to the first line with `--------` (if it exists) — that would allow test suites to generate a summary block that provides a little more detail (e.g. one line per failure/skip)

**Comment by gaborcsardi** [comment]
It would be nice to have a solution for this that does not require looking at the test(that) output, as that depends on the reporter, and even the reporter output changes occasionally.

testthat could write the results of the tests into some temporary cache file, maybe? That could be also used to rerun the tests that have failed, or to just show the latest results. Of course it is not easy where to write this file and when to remove it, etc.

**Comment by hadley** [comment]
I don't think the reporter is likely to be variable in this case; it requires considerable effort to use something other than `CheckReporter` in R CMD check. 

OTOH now that we always capture all the test output in GHA, it's fine to close this issue; I don't have any pressing need for it.
