### ISSUE TITLE
Extract XML test report from rcmdcheck::rcmdcheck

### ISSUE THREAD

**Issue by alessap** [r-lib/rcmdcheck#122]
Hi All,

This is probably a duplicate, however, as written in this [example](https://github.com/r-lib/r-azure-pipelines/blob/master/templates/pkg-rcmd_check.yml) it seems that a JUnit XML report can be obtained from `rcmdcheck`. I am not able to reproduce this on my end and I have also seen that extracting tests output is not yet implemented ([r-lib/rcmdcheck/issues/67](https://github.com/r-lib/rcmdcheck/issues/67)). 

Am I missing something, or is it not possible to get the test report in XML format from `rcmdcheck`?

Best regards,
Alessandro

**Comment by gaborcsardi** [comment]
You can run the test using the JUnit reporter, and then get the output file, just like in the example you referenced.

**Comment by alessap** [comment]
Thank you for your quick answer @gaborcsardi, but the XML report file is not created when I run:

`options(testthat.output_file = 'junit_result.xml');`
`rcmdcheck::rcmdcheck(check_dir = 'check', error_on = 'error');`

whilst it is created if I run:

`options(testthat.output_file = 'junit_result.xml');`
`test_results <- devtools::test(reporter = 'junit');` 

It would be nice to not run the tests twice and get the XML report from `rcmdcheck::rcmdcheck`.

**Comment by gaborcsardi** [comment]
You need to modify the `testthat.R` file to use the JUnit reporter: 
```r
test_check("<pkg>s", reporter = "junit")
```

**Comment by alessap** [comment]
Thank you so much for the help. That worked!
