### ISSUE TITLE
args argument to rcmdcheck has surprising behaviour

### ISSUE THREAD

**Issue by rorynolan** [r-lib/rcmdcheck#124]
I find that `rcmdcheck(args = c("--no-examples", "--no-tests"))` works fine but `rcmdcheck(args = "--no-examples --no-tests")` does not work; instead it warns `Warning: unknown option ‘--no-tests --no-examples’` and carries on and performs the tests and examples. This is surprising behaviour, particularly for someone who is used to running `R CMD CHECK` from the command line. There may be a reason for this, but if so it would be good to make clear in the docs that the spaced approach will _not_ work with `rcmdcheck()`.

**Comment by rorynolan** [comment]
From the labels, am I to take it that this is a documentation issue and you're comfortable that the behaviour is what you want? If so, I'm happy to do a documentation PR.

**Comment by gaborcsardi** [comment]
The behavior is the correct one and it is also very hard to change. To accept a single "argument string", we would need to call a shell (sh, bash on Unix, cmd on Windows), and that makes everything much less stable and more complicated. For example, you would need to shell quote everything, which is practically impossible in a cross platform way.

**Comment by rorynolan** [comment]
The merging of #125 resolves this issue.
