### ISSUE TITLE
Control `inst/doc` cleaning of pkgbuild

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rcmdcheck#130]
From #129

**Comment by bbolker** [comment]
You said something [here](https://github.com/r-lib/rcmdcheck/issues/129#issuecomment-723555347) that made it sound as though adding `Config/build/clean-inst-doc: false` to the `DESCRIPTION` file would disable the annoying (to me, no claims as to whether this is best practice or not!) "Building the package will delete..."  behaviour when there is a pre-built vignette in `inst/doc`. This doesn't seem to do what I want: any chance you could point me to documentation (or an appropriate place in the code) where I can read more/figure out how this works?

**Comment by gaborcsardi** [comment]
This issue is about implementing that feature.

**Comment by bbolker** [comment]
Great, thanks! I was confused (i.e., I thought it already existed).
