### ISSUE TITLE
Ignore known NOTEs

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rcmdcheck#131]
Would you support configuring the `NOTEs` that are expected during `R CMD check`, e.g. "installed size is", and handle them differently if `error_on = "note"` is set? Currently this NOTE requires a change of the GHA workflow in some packages, something I'd rather avoid doing: https://twitter.com/mdneuzerling/status/1331705185194807296.

We could add a `Config/rcmdcheck/known_notes: installed size is` that accepts regular expressions separated by comma and whitespace.

**Comment by gaborcsardi** [comment]
This is basically the duplicate of #12.

**Comment by krlmlr** [comment]
Thanks for the pointer.
