### ISSUE TITLE
rcmdcheck is not building the pdf manual

### ISSUE THREAD

**Issue by aravind-j** [r-lib/rcmdcheck#137]
When running `rcmdcheck` as follows as the `--no-manual` argument is missing, the source package being built for testing should include the pdf manual. However, the `Rd` files are not being converted to latex and then pdf.

```
rcmdcheck::rcmdcheck(args = c("--as-cran"), error_on = "warning")
```

So I am getting the following error.

```
 Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.
```

As I see, `rcmdcheck:::build_package` does not build the pdf manual.

```
rcmdcheck:::build_package(path = ".", tmpdir = tempdir(),
                          libpath = .libPaths(), quiet = FALSE, build_args = "")
```

Alternatively with `devtools::build` the pdf manual is built.

```
devtools::build(path = ".", binary = FALSE, manual = TRUE)
```

**Comment by gaborcsardi** [comment]
FWIW you can build the `tar.gz` first, and call `rcmdcheck()` on that, to work around it.
