### ISSUE TITLE
check title length

### ISSUE THREAD

**Issue by topepo** [r-lib/rcmdcheck#138]
Just received this (new?) rule in CRAN review: 

> Please reduce the length of the title to less than 65 characters.

**Comment by gaborcsardi** [comment]
rcmdkcheck only runs `R CMD check`, it does not (yet?) have extra checks.

**Comment by topepo** [comment]
I thought that we had added parts that we only see in CRAN reviews. Apologies.

**Comment by gaborcsardi** [comment]
No worries, maybe we could add to the list at https://github.com/DavisVaughan/extrachecks, it is not yet there AFAICT.
