### ISSUE TITLE
read_char() chokes on input with an invalid encoding

### ISSUE THREAD

**Issue by cpsievert** [r-lib/rcmdcheck#152]
I came across this by running `revdepcheck::cloud_report()` on shiny and it seems @hadley was seeing the same thing in https://github.com/r-lib/revdepcheck/issues/288 and attempted to fix in https://github.com/r-lib/rcmdcheck/pull/133, but that was never merged. In my case, I was seeing:

```
Processing package results  42% (ipc)
Error in readChar(path, nchars = file.info(path)$size, ...) : 
  invalid UTF-8 input in readChar()
```

It turns out the error was coming from [this call](https://github.com/r-lib/revdepcheck/blob/a2ece659e4838d6f122a41a21ab4b2625af75aa9/R/cloud.R#L283) to `rcmdcheck:::get_test_fail()` which in turns calls `rcmdcheck:::read_char()`

I can reproduce the error locally by trying to read in `{ipc}`'s `testthat.Rout.fail` file  the same way as `rcmdcheck:::read_char()`:

```r
path <- "ipc-testthat.Rout.fail"
readChar(path, nchars = file.info(path)$size)
#> Error in readChar(path, nchars = file.info(path)$size) : 
#>  invalid UTF-8 input in readChar()
```

With `useBytes = TRUE`, I can successfully read the file, but another downstream failure happens in [`rcmdcheck:::get_test_fail()`'s call to `nchar()`](https://github.com/r-lib/rcmdcheck/blob/a34ed2a360b4bc30876eb3813c2621aa18150bbb/R/parse.R#L93) (I'm guessing this is why @hadley said https://github.com/r-lib/rcmdcheck/pull/133#issuecomment-743306383)

```r
txt <- readChar(path, nchars = file.info(path)$size, useBytes = TRUE)
nchar(txt)
#> Error in nchar(txt) : invalid multibyte string, element 1
```

However, if I change the encoding to UTF-8, then it works:

```r
Encoding(tx)
#> "unknown"
nchar(enc2utf8(txt))
#> [1] 12252
```

**Comment by jimhester** [comment]
Yeah I think we can assume the tests were run in UTF-8.
