### ISSUE TITLE
Need to look at the exit status as well

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rcmdcheck#181]
To see if the check process exited because of some error. E.g. if there is no internet, or something like https://github.com/r-lib/devtools/issues/2376

**Comment by krlmlr** [comment]
What do we need to do here in addition to

https://github.com/r-lib/rcmdcheck/blob/17fa0544b6c9c4f9053449e89a84147b5c50f669/R/package.R#L242-L249

?

**Comment by gaborcsardi** [comment]
Yeah, I don't really know what this was about. Thanks for taking a look!

**Comment by vladimirobucina** [comment]
@gaborcsardi we're experiencing same problem in our pipeline, what was done to solve this?
