### ISSUE TITLE
Add --no-manual to build_args when it is set in args

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/rcmdcheck#191]
This command

    rcmdcheck(args="--no-manual")

will try to build the manual in the `R CMD build` step.  This confuses people, e.g. see this thread:  https://stat.ethz.ch/pipermail/r-package-devel/2022q3/008405.html .  `rcmdcheck` should add `--no-manual` to `build_args` if it is set in `args`.

**Comment by gaborcsardi** [comment]
`--no-manual` means something different for `R CMD build` and `R CMD check`, so we are not going to do this, I am afraid.
