### ISSUE TITLE
Fails to detect used libraries on code

### ISSUE THREAD

**Issue by latot** [r-lib/rcmdcheck#218]
Hi all, I have uploaded a sample, when we run ```rcmdcheck::rcmdcheck``` we can found this message:

```R
N  checking dependencies in R code ...
   Namespace in Imports field not imported from: ‘geotypes’
     All declared Imports should be used.
```

So, what is the point, is that ```geotypes``` is being used on the library, also if you try replace ```geotypes``` with a function from for example ```typed``` library there is no errors.

No idea why this happens.

[bug_typed.zip](https://github.com/r-lib/rcmdcheck/files/13529642/bug_typed.zip)

geotypes lib: https://github.com/CIT-UAI/geotypes

Thx!

**Comment by gaborcsardi** [comment]
It is very unlikely that this is an issue with rcmdcheck. Most likely you are not importing anything from the geotypes package, even though you put it in `Imports` in `DESCRIPTION`.
