### ISSUE TITLE
Mimic rcmd interface

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#26]
With `rcmd_process_options` and `rcmd_process$new(opts)`

**Comment by gaborcsardi** [comment]
Makes sense. I didn't do it, because `rcmdcheck()` does not have a lot of arguments, unlike `rcmd()`. Still, I think `*_options()` ended up not too bad, so `rcmdcheck()` could do the same.

**Comment by hadley** [comment]
This no longer seems important to me.
