### ISSUE TITLE
Provide rcmdcheck_error class

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#36]
```R
rcmdcheck_error <- function(old, new, package, version, maintainer) {
  structure(
    list(
      old = old,
      new = new,
      cmp = NULL,
      package = package,
      version = version,
      maintainer = maintainer
    ),
    class = "rcmdcheck_error"
  )
}
```

And appropriate methods for comparison.

**Comment by gaborcsardi** [comment]
@hadley Do you happen to remember what exactly this was for? For a single failure? What is `old`  and `new`?

**Comment by hadley** [comment]
I don't 😞   I have a vague feeling it's about making the S3 infrastructure a bit more robust

**Comment by gaborcsardi** [comment]
That would indeed make sense.

**Comment by gaborcsardi** [comment]
I'll postpone this to the next release.

**Comment by gaborcsardi** [comment]
I think much of this is in place already. The check result has an S3 class. I'll document this better in the README, and see if it makes sense to create more classes.

**Comment by gaborcsardi** [comment]
OK, I extended the README, I think for now it is good. Will add more methods as needed for revdepcheck.
