### ISSUE TITLE
Warning when running devtools::check(): Conversion of ‘README.md’ failed

### ISSUE THREAD

**Issue by jrosen48** [r-lib/rcmdcheck#45]
I think this is the right spot for this type of question, although if this belongs with [devtools](https://github.com/hadley/devtools), please excuse me.

When I run devtools::check() on the package in [this repository for the package prcr](https://github.com/jrosen48/prcr), this warning is output:

```
Conversion of ‘README.md’ failed:
pandoc: Could not fetch README-unnamed-chunk-2-1.png
README-unnamed-chunk-2-1.png: openBinaryFile: does not exist (No such file or directory)
```

The file named in the message - `README-unnamed-chunk-2-1.png` - is present in the root directory of the package. I updated devtools and its dependencies before posting this issue.

**Comment by jrosen48** [comment]
I just realized I had `*.png` in `.gitignore`.

**Comment by jrosen48** [comment]
That actually didn't seem to resolve the issue - the same warning is printed. 

Should the following be in `.Rbuildignore`? 

```
^README\.Rmd$
^README-.*\.png$
```

**Comment by hadley** [comment]
Images used in the readme should now go in `man/figures` and shouldn't be git ignored.  For questions of this nature, I'd now recommend community.rstudio.com/
