### ISSUE TITLE
Output tweaks

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#48]
```
> rcmdcheck::rcmdcheck()
───────────────────────────────────────────────────────────
─  using log directory ‘/private/tmp/RtmpxSAh2i/file541449c5ca53/boxes.Rcheck’
...
   
── R CMD check results ────────────── boxes 0.0.0.9000 ────
Duration: 17.2s



── Summary ────────────────────────────────────────────────

Check directory: '/private/tmp/RtmpxSAh2i/file541449c5ca53/boxes.Rcheck'
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

* I think the initial rule is unnecessary
* There's a lot of white space between `R CMD check results` and `Summary`
* Do we need a separate subheading for summary?
* Do we need to print the check directory at both the beginning and the end?

**Comment by gaborcsardi** [comment]
* OK, no initial rule.
* Agreed about whitespace
* No, I don't think so.
* Probably not. The first one is from `R CMD check`, and it is included, even if the check dir was later removed. The second one is only printed if the check dir is still there.
