### ISSUE TITLE
Variant that exits (with a non-zero error code) if the check fails

### ISSUE THREAD

**Issue by jimhester** [r-lib/rcmdcheck#51]
This is useful for use in CI systems which fail the build when a command returns a non-zero exit status.

Could be a option in the `print.rcmdcheck` method or just an option in `rcmdcheck::rcmdcheck()` directly maybe.

**Comment by gaborcsardi** [comment]
IDK, it feel awkward if a function call can exit from your session. Maybe this could be handled by the script that calls it? E.g. 

```
R -e 'rc <- rcmdcheck::rcmdcheck(); q(status = length(failures(rc)))'
```

(The `failures` function does not exist currently.)

**Comment by gaborcsardi** [comment]
Or we can have another function that is a small wrapper?

**Comment by jimhester** [comment]
Yeah another function would work. It doesn't have to call `q()`, it can just return an error with `stop()` and that sets the exit status appropriately if it is the last command.

```shell
$ R -q -e 'stop()'
> stop()
Error:
Execution halted
$ echo $?
1
```

**Comment by gaborcsardi** [comment]
Yeah, `stop` is better.

**Comment by gaborcsardi** [comment]
Do you want to fail on NOTEs as well? Probably not, right?

**Comment by gaborcsardi** [comment]
Btw. why would you run `rcmdcheck` on the CI, instead of just `R CMD check`?

**Comment by ClaytonJY** [comment]
Jim started this partially from a discussion we had on Ropensci; I want to use `rmdcheck` in CI because I think it (or `devtools::check` currently) gives superior output, and because I want my CI output to match what I get locally with RStudio + `devtools`. No more "why do I get these complaints locally, but not on CI?".

**Comment by jimhester** [comment]
I think having an option whether to stop for errors, warnings or notes makes the most sense.

**Comment by gaborcsardi** [comment]
But you don't actually want to stop when a NOTE/WARNING/ERROR happens, right? Only after the check is complete?

**Comment by jimhester** [comment]
Yeah

**Comment by gaborcsardi** [comment]
OK, added an `error_on` argument, please check it out.
