### ISSUE TITLE
Use `cli` package for output 

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rcmdcheck#52]

**Comment by jimhester** [comment]
I assume the lack of using cli is why we get things like

```
<U+2714>  checking for file 'devtools/DESCRIPTION'
```

Using the RStudio build pane. Although I am not really sure where the output is getting passed into the native encoding here, maybe within RStudio?

**Comment by gaborcsardi** [comment]
That's some bug, maybe in clisymbols. But yeah, we can try cli.

**Comment by gaborcsardi** [comment]
@jimhester I can't reproduce  the  `<U+2714>`, some details?

**Comment by gaborcsardi** [comment]
We don't use clisymbols any more now, more cli will come in later versions.

**Comment by jimhester** [comment]
With the latest rcmdcheck the build pane now shows `v` rather than the unicode checks, which I guess is OK.

Also to reproduce you can install rcmdcheck on windows and then use devel devtools + `build->check` in RStudio.

**Comment by gaborcsardi** [comment]
Oh, Windows of course. Yeah, I am afraid `v` is  correct.

**Comment by gaborcsardi** [comment]
We use cli now.
