### ISSUE TITLE
Introduce argument to supply directory with R CMD check output

### ISSUE THREAD

**Issue by helix123** [r-lib/rcmdcheck#59]
I would love to have an argument to supply directory with R CMD check output. Currently, it seems on Windows a random temporary directory is used as output of the R CMD check.

**Comment by gaborcsardi** [comment]
What would you do if the directory already exists?

**Comment by gaborcsardi** [comment]
So you can actually already do this by adding `--output=...` to  `args`, but it does make sense to  have an argument. We can just let `R CMD check` overwrite the check dir if it already exists...
