### ISSUE TITLE
Provide rcmdcheck_detail class?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rcmdcheck#63]
What would be a good way to make the output of `rcmdcheck::check_details()` look nice, maybe add a `"class"` attribute to the returned value list? I'd like to print all logs in an `"after_script"` step in tic.

We could also just add a `"class"` attribute to the character vectors. Do you have classes somewhere that format as bullet points or text, with color?

**Comment by gaborcsardi** [comment]
This is kinda hard, because some members are scalar strings, others not, some are  short, others long, etc.

**Comment by gaborcsardi** [comment]
I am postponing this now, as it is not clear how to implement it "better" than the current default  print method.

**Comment by gaborcsardi** [comment]
I am closing this now, we don't really have a pretty-printer for lists currently, and although it would be useful in general, I won't invent one now in this package.
