### ISSUE TITLE
Check with no suggested packages installed

### ISSUE THREAD

**Issue by hadley** [r-lib/rcmdcheck#64]
For stricter checking of (e.g.) tidyverse packages

**Comment by gaborcsardi** [comment]
That's a good idea, but it is a substantial change, because rcmdcheck does not manipulate libraries currently. It could, though.

**Comment by gaborcsardi** [comment]
See comments at https://github.com/r-lib/rcmdcheck/issues/50#issuecomment-489995717

**Comment by hadley** [comment]
I think this can now be closed since (I'm pretty sure) there's now an R CMD check env var for this.
