### ISSUE TITLE
signal an error when rcmdcheck objects are printed with check errors

### ISSUE THREAD

**Issue by jimhester** [r-lib/rcmdcheck#65]
The RStudio IDE currently uses `devtools::check()` (if installed) and cleans up (or not) the check directory based on the error code of the R process. https://github.com/rstudio/rstudio/issues/2235

Because there is no R error when using devtools / rcmdcheck this means that the package directory is always cleaned regardless of check status, so it can be difficult to debug the issue.

One way around this limitation would be to modify `print.rcmdcheck` to `stop()` if there are check errors (maybe warnings as well?) when run non-interactively. This would stop execution and set the error code (which RStudio could detect).

**Comment by gaborcsardi** [comment]
There is an `error_on` argument in `rcmdcheck::rcmdcheck()`, so that is not right place to handle this?

**Comment by jimhester** [comment]
Oh right, yeah that is probably it then, I now seem to recall us having a similar conversation previously

**Comment by jimhester** [comment]
So one issue with the current behavior is that it does not print the `rcmdcheck` object before exiting, which means that you don't get the check summary and full text of the `testthat.Rout.fail` file (if one exists).

**Comment by gaborcsardi** [comment]
But it is printing it as it goes, no? Like in the gif: https://github.com/r-lib/rcmdcheck/blob/master/inst/rcmdcheck.gif

**Comment by gaborcsardi** [comment]
Or that is suppressed? So do you want to print it before throwing the error?

**Comment by jimhester** [comment]
No it does print as it goes, but the `testthat.Rout.fail` file is only printed when the object is printed

**Comment by jimhester** [comment]
https://github.com/r-lib/rcmdcheck/blob/226cd044309d513002bee2239d37245bb7ec72d6/R/print.R#L37-L42

**Comment by jimhester** [comment]
Otherwise you only get the last 13 lines from the test failure, like when you run `R CMD check` from the command line.

**Comment by gaborcsardi** [comment]
Oh, ok. I guess we should just print that at the end if `quiet = FALSE` (the default) Is that good enough?

**Comment by jimhester** [comment]
Sure, sounds good to me

**Comment by gaborcsardi** [comment]
it is time for an `rcmdcheck` release, anyway.
