### ISSUE TITLE
Polluted reference output for examples

### ISSUE THREAD

**Issue by helix123** [r-lib/rcmdcheck#70]
The issue I raised at `devtools` (https://github.com/r-lib/devtools/issues/1655) is still present. It was suggested to file an issue with `rcmdcheck`.

**Comment by gaborcsardi** [comment]
How can I reproduce this?

**Comment by helix123** [comment]
I get the polluted file when I use RStudio on Windows and press "Check" in the "Build" pane. RStudio is configured to use `devtools` for checks. I let these additional options be passed  to `R CMD INSTALL` via RStudio (but doubt they are necessary for replication): `--no-multiarch --with-keep.source`.

**Comment by gaborcsardi** [comment]
So, this  is actually a devtools issue, because  devtools always uses `--timings`, so maybe it needs an argument to make  this optional?
