### ISSUE TITLE
revdep_check ignores libpath

### ISSUE THREAD

**Issue by helix123** [r-lib/rcmdcheck#71]
It seems, `revdep_check` ignores argument `libpath` when set to a character, e.g. `"C:/Users/username/rlibs"`. What happens is that it tries to write to the default library.
So, I can only pass a different libpath if I set the respective option and let the argument libpath with its default value (` libpath = getOption("devtools.revdep.libpath")`).

**Comment by gaborcsardi** [comment]
Moved to revdepcheck repo.
