### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by jimhester** [r-lib/rcmdcheck#75]
The devel version of devtools needs the devel version of rcmdcheck (for https://github.com/r-lib/devtools/pull/1713)

So it would be great to have a CRAN release of the current devel version, even if no additional changes are made.

**Comment by gaborcsardi** [comment]
Yep.

**Comment by gaborcsardi** [comment]
I'll submit it today.

**Comment by gaborcsardi** [comment]
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [ ] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`
* [ ] Bump version (in DESCRIPTION and NEWS)
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [x] ~~`pkgdown::build_site()`~~
* [ ] Approve email
* [ ] Tag release
* [ ] Bump dev version
* [x] ~~Write blog post~~
* [x] ~~Tweet~~

**Comment by gaborcsardi** [comment]
Just waiting for xopen to be published and then it is good to go....

**Comment by gaborcsardi** [comment]
Finally submitted....
