### ISSUE TITLE
R CMD build ignores CXX_STD

### ISSUE THREAD

**Issue by pat-s** [r-lib/rcmdcheck#83]
Weird error, no clue if there is any relation to `rcmdcheck()`. However, I have no experience with setting compiler flags and I am wondering about the following behavior:

On Appveyor, the package gets installed successfully when using `devtools::document()` with `-std=gnu99` https://ci.appveyor.com/project/pat-s/mlr#L13401

A few lines down in the `rcmdcheck()` process R CMD build is called and its not using the c++99 standard and fails therefore: https://ci.appveyor.com/project/pat-s/mlr#L13695

I've even set `CXX_STD = CXX11` in `src/Makevars` but it seems to get ignored. 
Any help here would be highly appreciated!

**Comment by gaborcsardi** [comment]
Hi, I think this is probably a pkgbuild bug: https://github.com/r-lib/pkgbuild/pull/46

@jimhester is there a manual workaround to add this flag, until pkgbuild is updated on CRAN?

**Comment by pat-s** [comment]
Ah cool, that helps!

If there is no easy other option, maybe you can set `Remotes: r-lib/pkgbuild` in DESCRIPTION as a workaround until the CRAN version is released? This way I wouldn't have to use two forks on my side.

**Comment by jimhester** [comment]
There isn't a great workaround unfortunately, I am going to submit a new version of pkgbuild soon however, so this should be fairly transient

**Comment by gaborcsardi** [comment]
@pat-s Maybe you can call `R CMD build` manually, and then `rcmdcheck()` on the tarball. Then `pkgbuild::build()` won't be called.

**Comment by pat-s** [comment]
Worked, thanks! https://github.com/mlr-org/mlr/blob/ce23a4ea63a74e521d0136601cb0880d7f53481c/tic.R#L21-L23

**Comment by gaborcsardi** [comment]
This is fixed  in pkgbuild I believe.

**Comment by pat-s** [comment]
While the`pkgbuild` update removed the lock of predefined compiler flags, I am desperately trying to set them correctly on appveyor.

As the `pkgbuild` code shows, it looks for user `Makevars` files: https://github.com/r-lib/pkgbuild/commit/60162f8e33c91508aa6ffe2cd968699d188586b2

However, [creating one on appveyor](https://github.com/mlr-org/mlr/blob/3956f482127e31fddb965ab061afb7b5236eb7f9/appveyor.yml#L12) or setting a [pkg `Makevars`](https://github.com/mlr-org/mlr/blob/appveyor/src/Makevars) file as an alternative have no effect.
I also tried setting them as `build_args` but I thinks that's wrong: `rcmdcheck(build_args = "--configure-args=-std=gnu99")`

Spent hours already trying various options. I have no exp with CPP, just trying to get appveyor running again :/ Any help would be highly appreciated! 

Here is an exemplary failing build: https://ci.appveyor.com/project/mlr-org/mlr/builds/19737175

cc @jimhester
