### ISSUE TITLE
Option to disable progressive output (e.g. for CI use)

### ISSUE THREAD

**Issue by ilarischeinin** [r-lib/rcmdcheck#94]
I have been enjoying the new prettier output from `devtools::check()` on my local machine for a while (thank you!). Now that I updated the packages installed on our GitLab CI, I noticed that GitLab doesn't support progressive output (i.e. the UI outputs lines to the client browser as they appear), so the output of checking packages looks like this:

![screenshot 2018-11-15 at 11 05 17](https://user-images.githubusercontent.com/2540173/48541939-88bc2380-e8c6-11e8-9d29-68899c63d9bc.png)

This is an acknowledged issue on GitLab's side (mentioned at least in issues [#1021](https://gitlab.com/gitlab-org/gitlab-runner/issues/1021), [#12936](https://gitlab.com/gitlab-org/gitlab-ce/issues/12936), [#2154](https://gitlab.com/gitlab-org/gitlab-runner/issues/2154)). I saw a suggestion to wrap the CI command inside the command line tool `script`, which emulates a tty. As shown below, it does add colour to the output, but doesn't help with the progressive output (i.e. using `\r` to go back to the beginning of the line to overwrite it), as the output line has already been sent to the browser.

![screenshot 2018-11-15 at 11 14 44](https://user-images.githubusercontent.com/2540173/48542368-ad64cb00-e8c7-11e8-8b27-53e6d3775adc.png)

I know the bottomline issue here is with GitLab and not `rcmdcheck`, but would it be possible to add an option to disable progressive output for scenarios like this where it is not supported? It is of course a cosmetic issue, so not a high priority I'm sure. And depending on how complicated it would to implement, might not be worth the effort. I absolutely understand that and just thought I'd ask.

**Comment by gaborcsardi** [comment]
Can you set `quiet = TRUE`?

**Comment by ilarischeinin** [comment]
Sorry I should have mentioned this. I can and I tried it, but my preference would be to get the full output, but just without the "progressive" functionality. But like I said, it's a cosmetic issue, and I understand that depending on how things are implemented, adding that functionality could be too much work to be worth it.

**Comment by gaborcsardi** [comment]
I think we could just omit the `\r` output if the standard output is not a terminal. Then you don't need to use `script`, which apparently does not support `\r`?

**Comment by randy3k** [comment]
I think we need a global solution to avoid `"\r"` (or any escape chars) from being printed. `testthat` has a similar issue: https://github.com/r-lib/testthat/pull/746

**Comment by gaborcsardi** [comment]
OK, `\r` can be now turned off via the `R_CLI_DYNAMIC=FALSE` env var, and cli also tries to auto-detect whether it is supported, and turns it off if stdout is not a terminal. 

CIs might emulate a terminal, though, so you might still need to add the env var, or we can make the detection better, by detecting individual CIs that don't handle `\r`.
