### ISSUE TITLE
cant download rcmdcheck 

### ISSUE THREAD

**Issue by rajsaraiya009** [r-lib/rcmdcheck#98]
cannot install rcmdcheck following is the error, 

install.package(rcmdcheck)

 There is a binary version available but the source version is later:
          binary source needs_compilation
rcmdcheck  1.3.1  1.3.2             FALSE

**Comment by gaborcsardi** [comment]
I don't understand. This is not an error message, just a message. You can either  install the older binary or the newer source package.
